### ISSUE TITLE
Newer versions of opengl

### ISSUE THREAD

**Issue by BlobTheKat** [EnzoAlbornoz/nodegl#21]
It seems this project only supports OpenGL 1.x, where the latest is 4.x (specifically 4.6)

**Comment by EnzoAlbornoz** [comment]
OpenGL 1 has fewer API functions than the other versions, and writing all these bindings is really time-consuming. This repository explores native bindings to OpenGL. If you want some last-gen tech, I recommend you look into WebGL. It's natively present on Chrome, Deno, Bun, and many more JS runtimes.
